
## library(protoClasses)
library(devtools)
library(Rcpp)
library(coda)
library(abind)

devtools::load_all("../protoClasses")

source("R/utils.R")
source("R/fields.R")
source("R/sync.R")
source("R/valibuild.R")
source("R/S4.R")
source("R/mirror.R")
source("R/predict.R")
source("R/update.R")
source("R/transforms.R")
source("R/mcmc.R")           
source("R/pbm.R")
source("R/bc_root.R")
source("R/bc_core.R")
source("R/bc_acrej.R")
source("R/bc_tr.R")
source("R/distributions.R")
source("R/adapt.R")

Rcpp::sourceCpp("src/sample.cpp")
