## Sources("/Homes/vitoshka/Dropbox/works/R_dev/Classes/protoClasses.R")
## source("/home/vitoshka/Dropbox/works/R_dev/pbm/funcs.R")
## library(Rgraphviz)
## load_all("~/works/protoClasses/")

## library(protoClasses)
## library(coda)
## library(abind)
## source("~/dev/pbm/R/utils.R")
## source("~/dev/pbm/R/fields.R")
## source("~/dev/pbm/R/sync.R")
## source("~/dev/pbm/R/valibuild.R")
## source("~/dev/pbm/R/S4.R")
## source("~/dev/pbm/R/mirror.R")
## source("~/dev/pbm/R/predict.R")
## source("~/dev/pbm/R/update.R")
## source("~/dev/pbm/R/transforms.R")
## source("~/dev/pbm/R/mcmc.R")           
## source("~/dev/pbm/R/pbm.R")
## source("~/dev/pbm/R/bc_root.R")
## source("~/dev/pbm/R/bc_core.R")
## source("~/dev/pbm/R/bc_acrej.R")
## source("~/dev/pbm/R/bc_tr.R")
## source("~/dev/pbm/R/distributions.R")
## source("~/dev/pbm/R/adapt.R")

## library(testthat)
## test_dir("~/works/pbm/tests/")
