# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rdunif <- function(min, max) {
    .Call('_pbm_rdunif', PACKAGE = 'pbm', min, max)
}

ddunif <- function(min, max) {
    .Call('_pbm_ddunif', PACKAGE = 'pbm', min, max)
}

